name: Build binary file

on: 
  push:
    branches:
      - 'main'
    paths:
      - '**.py'
      - '**.yml'

jobs:
  build:

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
      include:
        - os: ubuntu-latest
          ls: |
            ls -la
        - os: macos-latest
          ls: |
            ls -la
        - os: windows-latest
          ls: |
            ls

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python '3.10'
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Build single binary
        run: |
          python build.py
      - name: Show result
        run: |
          ${{ matrix.ls }} dist

