name: Build binary file

on: 
  push:
    branches:
      - 'main'
    paths:
      - '**.py'
      - '**.yml'

jobs:
  build:

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest, macos-latest]
        include:
          - os: ubuntu-latest
            file-postfix: linux86_64
            vr-rep: |
              sed -i "s/<VERSION>/$(git describe --tags)/" bot.py
              cat bot.py
          - os: macos-latest
            file-postfix: macos86_64
            vr-rep: |
              sed -i '.old' "s/<VERSION>/$(git describe --tags)/" bot.py
              cat bot.py
          - os: windows-latest
            file-postfix: win10.exe
            vr-rep: |
              $version = $(git describe --tags;)
              C:\"Program Files"\Git\usr\bin\sed.exe -i "s/<VERSION>/$version/" bot.py
              gc bot.py

    steps:
      - uses: actions/checkout@v3
      - run: git fetch --prune --unshallow
      - name: Set up Python '3.10'
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Replace version
        run: |
          ${{ matrix.vr-rep }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Build single binary
        run: |
          python build.py
      - name: Upload binary results
        uses: actions/upload-artifact@v3
        with:
          name: telegram-member-inviter-${{ matrix.file-postfix }}
          path: |
            dist/telegram-member-inviter
            dist/telegram-member-inviter.*

